version: 2
jobs:
  build:
    script:
      - $MAVEN_HOME/bin/mvn clean
    docker:
      - image: circleci/openjdk:8u181-jdk
      - image: circleci/mvn:3.8.1
    working_directory: ~/repo

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

